# Detect compiler version and enable C++17 if supported
if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
    if ("${CMAKE_CXX_COMPILER_VERSION}" VERSION_LESS "3.6")
        message(FATAL_ERROR "Please use Clang version 3.6 or newer to compile this project.")
    elseif ("${CMAKE_CXX_COMPILER_VERSION}" VERSION_LESS "5")
        message(WARNING "C++17 support with Clang ${CMAKE_CXX_COMPILER_VERSION} is experimental.")
        add_compile_options("-std=c++1z")
    else()
        add_compile_options("-std=c++17")
    endif()
elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
    if ("${CMAKE_CXX_COMPILER_VERSION}" VERSION_LESS "6")
        message(FATAL_ERROR "Please use GCC version 6 or newer to compile this project.")
    else()
        message(WARNING "C++17 support with GCC ${CMAKE_CXX_COMPILER_VERSION} is experimental.")
        add_compile_options("-std=c++17")
    endif()
elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
    add_compile_options("/std:c++17")
endif ()