# Tools
if (DEFINED SWARMIO_TARGET_ARCHITECTURE)
    set(CMAKE_C_COMPILER ${SWARMIO_TARGET_ARCHITECTURE}-gcc)
    set(CMAKE_CXX_COMPILER ${SWARMIO_TARGET_ARCHITECTURE}-g++)
else()
    set(CMAKE_C_COMPILER gcc)
    set(CMAKE_CXX_COMPILER g++)
endif()

# Version
if (NOT "${SWARMIO_GCC_VERSION}" STREQUAL "")
    set(CMAKE_C_COMPILER "${CMAKE_C_COMPILER}-${SWARMIO_GCC_VERSION}")
    set(CMAKE_CXX_COMPILER "${CMAKE_CXX_COMPILER}-${SWARMIO_GCC_VERSION}")
endif()

# Include platform definition
include("${CMAKE_CURRENT_LIST_DIR}/linux.cmake")